# Site Settings
title: My Resume
url: 'https://jghward.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Jon Ward
tagline: Cloud Infrastructure Engineer
pic: jonward.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "DevOps-fuelled Linux sysadmin and cloud architect. Passionate about creating automated, scalable infrastructure-as-code."
# 'Summarise your career here lorem ipsum dolor sit amet, consectetuer adipiscing elit.
#You can <a href="#" target="_blank">download this free resume/CV template here</a>. Aenean
#commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient
#montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.'

#sidebar links
email: hello@jghward.com
website: jghward.com #do not add http://
linkedin: jghward
twitter: '@jghward'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-85275599-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

host: 192.168.0.16
